<br>

Light Theme Configuration

<details>
<summary>Click to Show Code</summary>

config.toml

base = "light"

primaryColor="#e8e3f6ff"      # A nice purple for accents
backgroundColor="#FFFFFF"   # White background
secondaryBackgroundColor="#F0F2F6" # Light gray for secondary areas
textColor="#ffffffff"       # Dark gray/black for text
font="sans serif"

</details>

<br>